spring.application.name=krishisetu

# Set SPRING_PROFILES_ACTIVE=prod in Koyeb
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}


# # Force the listener to start immediately
# spring.kafka.listener.auto-startup=true

# # Ensure the app doesn't hang if Kafka is slow to respond
# spring.kafka.admin.fail-fast=true

# # Explicitly set the listener type
# spring.kafka.listener.type=single

# # TRACE logging is the only way to see WHY it's not starting
# logging.level.org.springframework.kafka.listener.KafkaMessageListenerContainer=TRACE
# logging.level.org.apache.kafka.clients.consumer.internals.ConsumerCoordinator=TRACE